# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Leslie Peng'
tagline:          'Thoughts on life and code by Leslie.'
description:      'Thoughts on life and code.'
url:              https://lesliepeng.github.io
baseurl:          /
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"

author:
  name:           'LesliePeng'
  url:            https://lesliepeng.github.io
  email:          xiaomeng1207@gmail.com

version:          1.0.0
